apiVersion: apps/v1
kind: Deployment
metadata:
    name: pma
spec:
    selector:
        matchLabels:
            app: pma
    template:
        metadata:
            labels:
                app: pma
        spec:
            containers:
            - name: c-pma
              image: phpmyadmin/phpmyadmin
              ports:
              - containerPort: 80
              env:
              - name: PMA_HOST
                value: db