apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application.name}}-service-{{.Values.application.buildNumber}}
  labels:
    app: {{.Values.application.name}}
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: {{.Values.application.name}}
    version: {{.Values.application.buildNumber}}
