apiVersion: apps/v1
kind: Deployment
metadata:
    name: shorten-app-dev
spec:
    replicas: 3
    strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 1
      type: RollingUpdate    
    selector:
        matchLabels:
            app: shorten-app-dev
    template:
        metadata:
            labels:
                app: shorten-app-dev
            annotations:
              timestamp: "{{.Values.timestamp}}"                
        spec:
            containers:
            - name: c-shorten
              image: {{.Values.image.repository}}:{{.Values.image.tag}}
              ports:
              - containerPort: 80
              volumeMounts:
              - name: config
                mountPath: /var/www/html/.env
                subPath: .env
              - name: public
                mountPath: /var/www/html/public/storage
            imagePullSecrets:
            - name: dockerhub
            restartPolicy: Always                
            volumes:
            - name: public
              persistentVolumeClaim:
                claimName: app-public
            - name: config
              configMap:
                name: app-config
                items:
                - key: config
                  path: .env
