apiVersion: v1
kind: Service
metadata:
    name: shorten-app-dev
spec:
    type: NodePort
    ports:
    - nodePort: 30001
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
        app: shorten-app-dev