apiVersion: apps/v1
kind: Deployment
metadata:
    name: db
spec:
    selector:
        matchLabels:
            app: db
    template:
        metadata:
            labels:
                app: db
        spec:
            volumes:
            - name: storage
              persistentVolumeClaim:
                claimName: pvc-db
            containers:
            - name: c-mariadb
              image: mariadb
              volumeMounts:
              - name: storage
                mountPath: /var/lib/mysql
              ports:
              - containerPort: 3306
              env:
              - name: MYSQL_DATABASE
                value: laravel
              - name: MYSQL_ROOT_PASSWORD
                value: root
